// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceFlex_Backend.Data;

#nullable disable

namespace PriceFlex_Backend.Migrations
{
    [DbContext(typeof(ScrapperDbContext))]
    [Migration("20240623191725_fix-regex")]
    partial class fixregex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PriceFlex_Backend.Models.OnlineShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BasicUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LogoImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OnlineShopScrappers");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OnlineShopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnlineShopId");

                    b.HasIndex("UserId");

                    b.ToTable("ScrapperConfigs");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OnlineShopId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("ScrapperConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnlineShopId");

                    b.HasIndex("ScrapperConfigId");

                    b.HasIndex("UserId");

                    b.ToTable("ScrapperDatas");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllowedScrappers")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.OnlineShop", b =>
                {
                    b.HasOne("PriceFlex_Backend.Models.User", null)
                        .WithMany("OnlineShops")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperConfig", b =>
                {
                    b.HasOne("PriceFlex_Backend.Models.OnlineShop", null)
                        .WithMany("ScrapperConfigs")
                        .HasForeignKey("OnlineShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceFlex_Backend.Models.User", null)
                        .WithMany("ScrapperConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperData", b =>
                {
                    b.HasOne("PriceFlex_Backend.Models.OnlineShop", null)
                        .WithMany("ScrapperDatas")
                        .HasForeignKey("OnlineShopId");

                    b.HasOne("PriceFlex_Backend.Models.ScrapperConfig", "ScrapperConfig")
                        .WithMany("ScrapperDatas")
                        .HasForeignKey("ScrapperConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceFlex_Backend.Models.User", null)
                        .WithMany("ScrapperDatas")
                        .HasForeignKey("UserId");

                    b.Navigation("ScrapperConfig");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.OnlineShop", b =>
                {
                    b.Navigation("ScrapperConfigs");

                    b.Navigation("ScrapperDatas");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperConfig", b =>
                {
                    b.Navigation("ScrapperDatas");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.User", b =>
                {
                    b.Navigation("OnlineShops");

                    b.Navigation("ScrapperConfigs");

                    b.Navigation("ScrapperDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
