// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceFlex_Backend.Data;

#nullable disable

namespace PriceFlex_Backend.Migrations
{
    [DbContext(typeof(ScrapperDbContext))]
    partial class ScrapperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PriceFlex_Backend.Models.OnlineShopScrapper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OnlineShopScrappers");

                    b.HasData(
                        new
                        {
                            Id = 55,
                            Classes = ".main-price .whole",
                            CreatedAt = new DateTime(2024, 6, 17, 18, 13, 38, 770, DateTimeKind.Utc).AddTicks(276),
                            Name = "Media Expert",
                            UpdatedAt = new DateTime(2024, 6, 17, 18, 13, 38, 770, DateTimeKind.Utc).AddTicks(279),
                            Url = "https://www.mediaexpert.pl/komputery-i-tablety/laptopy-i-ultrabooki/laptopy/laptop-lenovo-ideapad-gaming-3-15ach6-15-6-ips-144hz-r5-5500h-16gb-ram-512gb-ssd-geforce-rtx2050-windows-11-home"
                        },
                        new
                        {
                            Id = 8,
                            Classes = ".main-price .whole",
                            CreatedAt = new DateTime(2024, 6, 17, 18, 13, 38, 770, DateTimeKind.Utc).AddTicks(282),
                            Name = "Vinted",
                            UpdatedAt = new DateTime(2024, 6, 17, 18, 13, 38, 770, DateTimeKind.Utc).AddTicks(282),
                            Url = "https://www.mediaexpert.pl/komputery-i-tablety/laptopy-i-ultrabooki/laptopy/laptop-lenovo-ideapad-gaming-3-15ach6-15-6-ips-144hz-r5-5500h-16gb-ram-512gb-ssd-geforce-rtx2050-windows-11-home"
                        });
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OnlineShopScrapperId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnlineShopScrapperId");

                    b.HasIndex("UserId");

                    b.ToTable("ScrapperPrices");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.OnlineShopScrapper", b =>
                {
                    b.HasOne("PriceFlex_Backend.Models.User", null)
                        .WithMany("OnlineShopScrappers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.ScrapperPrice", b =>
                {
                    b.HasOne("PriceFlex_Backend.Models.OnlineShopScrapper", null)
                        .WithMany("Prices")
                        .HasForeignKey("OnlineShopScrapperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceFlex_Backend.Models.User", null)
                        .WithMany("ScrapperPrices")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.OnlineShopScrapper", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("PriceFlex_Backend.Models.User", b =>
                {
                    b.Navigation("OnlineShopScrappers");

                    b.Navigation("ScrapperPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
